#
# Module manifest for module 'Project-ProgramB'
#
# Generated by: MarcusW
#
# Generated on: 12/08/2015
#

@{

# Script module or binary module file associated with this manifest

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '39040b17-35f2-40ee-8636-5545469e6315'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "ProjectA" modules.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModules")

# List of all modules packaged with this module
ModuleList = @("Project-ProgramB")

}

