#
# Module manifest for module 'Cmd'
#
# Generated by: Marcus Walther
#
# Generated on: 04/04/2019
#

@{
# Script module or binary module file associated with this manifest
RootModule = 'Cmd.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '0c95874c-e278-48eb-ae99-9ed4194f1cee'

# Author of this module
Author = 'Marcus Walther'

# Copyright statement for this module
Copyright = '(c) 2015 Marcus Walther.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "Cmd" environment.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModuleCore")

# List of all modules packaged with this module
ModuleList = @("Cmd")
}

