#
# Module manifest for module 'Cmd'
#
# Generated by: Marcus Walther
#
# Generated on: 12/08/2015
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'Cmd.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '0c95874c-e278-48eb-ae99-9ed4194f1cee'

# Author of this module
Author = 'Marcus Walther'

# Copyright statement for this module
Copyright = '(c) 2015 Marcus Walther. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "Notepad++" editor.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModules")

# Functions to export from this module
FunctionsToExport = @()

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all modules packaged with this module
ModuleList = @("Cmd")

}

