trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables: 
  suffix: '$(Build.BuildNumber)'
  nugetSource: 'https://pkgs.dev.azure.com/MarcusWalther/_packaging/Feed_EnvironmentModuleCore/nuget/v3/index.json'

steps:
- pwsh: sudo apt-get install nuget
  displayName: 'Installing nuget'

- task: NuGetAuthenticate@0

- pwsh: .\SetupEnvironment.ps1
  displayName: 'Setup the environment'

- pwsh: Push-Location; git submodule update --init; Set-Location Test; git fetch; git checkout -f develop; Pop-Location
  displayName: 'Checkout the Git submodules'

- pwsh: Invoke-Build Prepare -Suffix $(suffix) -NugetSource "$(nugetSource)" -AllowPrerelease
  displayName: 'Download the required binary libraries'

- pwsh: Invoke-Build Test -Suffix $(suffix)
  displayName: 'Test the module'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'TestResults/*.xml'
    failTaskOnFailedTests: true