trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables: 
  suffix: '$(Build.BuildNumber)'
  nugetSource: 'https://marcuswalther.pkgs.visualstudio.com/EnvironmentModuleCoreSrc/_packaging/EnvironmentModuleCoreSrc_Feed/nuget/v3/index.json'

steps:
- task: NuGetToolInstaller@1
- task: NuGetAuthenticate@0

- pwsh: .\SetupEnvironment.ps1
  displayName: 'Setup the environment'

- pwsh: git submodule update --init; git checkout develop ./Test
  displayName: 'Checkout the Git submodules'

- pwsh: Invoke-Build Prepare -Suffix $(suffix) -NugetSource "$(nugetSource)" -AllowPrerelease
  displayName: 'Download the required binary libraries'

- pwsh: Invoke-Build Test -Suffix $(suffix)
  displayName: 'Test the module'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'TestResults/*.xml'
    failTaskOnFailedTests: true