#
# Module manifest for module 'Abstract_Python'
#
# Generated by: MarcusW
#
# Generated on: 12/09/2018
#

@{

    # Script module or binary module file associated with this manifest
    RootModule = 'Abstract_Python.psm1'

    # Version number of this module.
    ModuleVersion = '1.0'

    # ID used to uniquely identify this module
    GUID = '2ee32fc2-2c1c-4b9f-bd68-c3b760f8fbb2'

    # Author of this module
    Author = 'Marcus W'

    # Copyright statement for this module
    Copyright = '(c) 2018 MarcusW.'

    # Description of the functionality provided by this module
    Description = 'This abstract environment module provides the framework for all "Python" functions.'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @("EnvironmentModuleCore")

    # List of all modules packaged with this module
    ModuleList = @("Abstract_Python")

}

