#
# Module manifest for module 'NotepadPlusPlus-x86'
#
# Generated by: Marcus Walther
#
# Generated on: 18/03/2019
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'NotepadPlusPlus-x86.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '145f6307-ba32-4e08-9904-5ed595011057'

# Author of this module
Author = 'Marcus Walther'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "Notepad++" editor.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModuleCore")

# List of all modules packaged with this module
ModuleList = @("NotepadPlusPlus-x86")

}