#
# Module manifest for module 'Project-ProgramB'
#
# Generated by: MarcusW
#
# Generated on: 12/08/2015
#

@{

    # Script module or binary module file associated with this manifest
    RootModule = 'Abstract-Project.psm1'

    # Version number of this module.
    ModuleVersion = '1.0'
    
    # ID used to uniquely identify this module
    GUID = '0a87cb4a-bb42-418c-8909-a6b7e8eeb65d'
    
    # Author of this module
    Author = 'Marcus W'
    
    # Copyright statement for this module
    Copyright = '(c) 2015 MarcusW. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'This environment module will provide some common project function'
    
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @("EnvironmentModules")
    
    # List of all modules packaged with this module
    ModuleList = @("Abstract-Project")    
}
    
    