#
# Module manifest for module 'Cmd-x86'
#
# Generated by: Marcus Walther
#
# Generated on: 12/08/2015
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'Cmd-x86.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '37d22918-1671-4f9c-a91f-5e61fa6b3303'

# Author of this module
Author = 'Marcus Walther'

# Copyright statement for this module
Copyright = '(c) 2015 Marcus Walther. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the cmd environment.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModules")

# Functions to export from this module
FunctionsToExport = @()

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all modules packaged with this module
ModuleList = @("Cmd-x86")

}

