#
# Module manifest for module 'Project-ProgramA'
#
# Generated by: MarcusW
#
# Generated on: 18/03/2019
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'Project-ProgramA.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'fc75d2cb-734d-4b59-aa49-1c3d8d78f6a0'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "ProjectA" modules.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModuleCore")

# List of all modules packaged with this module
ModuleList = @("Project-ProgramA")

}

