#
# Module manifest for module 'NotepadPlusPlus-x64'
#
# Generated by: Marcus Walther
#
# Generated on: 12/08/2015
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'NotepadPlusPlus-x64.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '2458903f-ca40-412b-bdb3-c1de8e70395d'

# Author of this module
Author = 'Marcus Walther'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "Notepad++" editor.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModules")

# List of all modules packaged with this module
ModuleList = @("NotepadPlusPlus-x64")

}