#
# Module manifest for module 'Aspell-2_1-x86'
#
# Generated by: Marcus Walther
#
# Generated on: 12/08/2015
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'Aspell-2_1-x86.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '145f6307-ba32-4e08-9904-5ed595011057'

# Author of this module
Author = 'Marcus Walther'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This environment module will add the Aspell program to the PATH.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModules")

# Functions to export from this module
FunctionsToExport = @()

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all modules packaged with this module
ModuleList = @("Aspell-2_1-x86")

}

